# Docker-specific configuration
micronaut:
  application:
    name: ai-monitor-api
  server:
    port: 8082
    host: 0.0.0.0  # Important: bind to all interfaces in container
    cors:
      enabled: true
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET:docker-dev-secret-change-in-production}"
    intercept-url-map:
      - pattern: /hello
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /api/v1/metrics/**
        http-method: GET
        access:
          - isAnonymous()

datasources:
  default:
    url: jdbc:postgresql://db:5432/newdle_db
    username: newdle_user
    password: newdle_password
    driverClassName: org.postgresql.Driver
    # Retry config (Micronaut Data 4+)
    schema-generate: NONE
    dialect: POSTGRES
    health:
      enabled: true
    # Retry settings
    options:
      connect-retry-attempts: 30
      connect-retry-delay: 1000 # milliseconds
    hikari:
      initializationFailTimeout: -1

logger:
  levels:
    com.aimonitor: INFO
    io.micronaut.http: INFO
    root: INFO

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

kafka:
  bootstrap-servers: kafka:9092
  consumers:
    default:
      value-deserializer: io.micronaut.configuration.kafka.serde.JsonObjectDeserializer
      value-type: aimonitor.micronaut.InferenceLog
  consumer:
      group-id: ai-monitor-group
      auto-offset-reset: earliest
      enable-auto-commit: true
  producer:
      acks: all

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:migration
